### PR TITLE
Add ffmpeg 4.4 patch

### LINKED ISSUE #10: Missing AVStream member
I needed to compile the package, but it fails with message:
```
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:183:21: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘codec’
  183 |         if (stream->codec->codec_type == AVMEDIA_TYPE_AUDIO)
      |                     ^~~~~
```
It is follows with other codelines with the same issue.

### PR DESCRIPTION
**Pull request by M1CK431**
I dunno how to fully test it locally but i guess it should be something like that :man_shrugging: 
Hopefully fix #10

### CODE REVIEW

**Comment by M1CK431** [comment]
Mmmm after downgrading poppler, I still have the same ffmpeg error so I guess Openboard don't care about my patch... :cry:

**Comment by fsiegert** [comment]
Hi @M1CK431,

is this really having any affect on the compilation on Linux? It looks like you are changing `OpenBoard.pro` in the `macx { ... }` section, don't you?

Best,  
Frank

**Comment by M1CK431** [comment]
> Hi @M1CK431,
> 
> is this really having any affect on the compilation on Linux? It looks like you are changing `OpenBoard.pro` in the `macx { ... }` section, don't you?
> 
> Best, Frank

You are right, as I explained a few minutes after opening this PR, I discover that my patch have just no effect during linux build :cry: 

Since I have no other idea (it's the first time I take a look in a C++/QT project) about how to fix it and because I see that there is another issue with poppler, I have just replace it with xournalpp on my computer, waiting for a fix of openboard.

To be crystal clear, I like openboard and I do my best to help with it, but it seems that there is an issue at upstream side to handle a lot of deprecation / outdated dependencies, at least mid-term. I hope this situation will change soon, otherwise I fear that it will become impossible to use it with ArchLinux :crossed_fingers: 

In the meantime, if you have an idea of files I should take a look on to solve the ffmpeg issue, I'm still happy to help! :heart:

**Comment by fsiegert** [comment]
Ok, I have one idea that I'm trying out now, will let you know.

**Comment by fsiegert** [comment]
Apparently this worked, have fixed it in the AUR:
https://aur.archlinux.org/cgit/aur.git/commit/?h=openboard&id=c39644d53595b4d1974460ae6318e6194f4cc4cd

Can you try it now?

This pull request can be closed then.

**Comment by M1CK431** [comment]
I just try and it works perfectly :ok_hand: 
Thanks a lot for your good wook and so sorry for this useless "help".
Closing that PR right now.

**Pull request closed without merging**
